name: urban_mobility
version: "1.0.0"
config-version: 2
profile: urban_mobility
model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: target
clean-targets: ["target", "dbt_packages"]

flags:
  send_anonymous_usage_stats: false

models:
  urban_mobility:
    staging:
      +materialized: view
    dimensions:
      +materialized: table
    facts:
      +materialized: table
    marts:
      +materialized: table
