select
    cast(trip_id as varchar) as trip_id,
    cast(stable_record_hash as varchar) as stable_record_hash,
    cast(source_row_number as bigint) as source_row_number,
    cast(vendor_id as bigint) as vendor_id,
    cast(pickup_datetime as timestamp) as pickup_datetime,
    cast(dropoff_datetime as timestamp) as dropoff_datetime,
    cast(passenger_count as double) as passenger_count,
    cast(trip_distance as double) as trip_distance,
    coalesce(cast(rate_code_id as integer), 0) as rate_code_id,
    cast(store_and_fwd_flag as varchar) as store_and_fwd_flag,
    cast(pickup_zone_id as integer) as pickup_zone_id,
    cast(dropoff_zone_id as integer) as dropoff_zone_id,
    coalesce(cast(payment_type as integer), 0) as payment_type,
    cast(fare_amount as double) as fare_amount,
    cast(extra as double) as extra,
    cast(mta_tax as double) as mta_tax,
    cast(tip_amount as double) as tip_amount,
    cast(tolls_amount as double) as tolls_amount,
    cast(improvement_surcharge as double) as improvement_surcharge,
    cast(total_amount as double) as total_amount,
    cast(congestion_surcharge as double) as congestion_surcharge,
    cast(airport_fee as double) as airport_fee,
    cast(duration_minutes as double) as duration_minutes,
    cast(average_speed_mph as double) as average_speed_mph,
    cast(revenue_per_mile as double) as revenue_per_mile,
    cast(is_airport_trip as boolean) as is_airport_trip,
    cast(quality_status as varchar) as quality_status,
    cast(quality_reasons as varchar) as quality_reasons,
    cast(service as varchar) as service,
    cast(source_year as integer) as source_year,
    cast(source_month as integer) as source_month,
    cast(source_file as varchar) as source_file,
    cast(ingested_at as timestamp) as ingested_at
from {{ source("mobility_staging", "yellow_trips") }}
